version: "3.8"

services:

  configserver:
    image: harishmoolchandani/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - eazybank-network

  accounts:
    image: harishmoolchandani/accounts:latest
    mem_limit: 700m
    ports:
      - "7080:8080"
      - "7081:8080"
    networks:
      - eazybank-network
    depends_on:
      - configserver
    deploy:
        restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 120s
    environment:
        SPRING_PROFILES_ACTIVE: default
        SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      
  cards:
    image: harishmoolchandani/cards:latest
    mem_limit: 700m
    ports:
      - "8000:9000"
      - "8001:9000"
    networks:
      - eazybank-network
    depends_on:
      - configserver
    deploy:
        restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 120s
    environment:
        SPRING_PROFILES_ACTIVE: default
        SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
        
  loans:
    image: harishmoolchandani/loans:latest
    mem_limit: 700m
    ports:
      - "7090:8090"
      - "7091:8090"
    networks:
      - eazybank-network
    depends_on:
      - configserver
    deploy:
        restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 120s
    environment:
        SPRING_PROFILES_ACTIVE: default
        SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
networks:
  eazybank-network: